// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7zgBTwbPpHbjHNGdtqUv3x
// Component: 81QPYdqQ8Y
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 7zgBTwbPpHbjHNGdtqUv3x/projectcss
import sty from "./PlasmicEnterCode.module.css"; // plasmic-import: 81QPYdqQ8Y/css

import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: 0TsNv0K1B/icon
import Icon16PxCheckIcon from "./icons/PlasmicIcon__Icon16PxCheck"; // plasmic-import: XZAvKNBJmZ/icon
import Rectangle116Icon from "./icons/PlasmicIcon__Rectangle116"; // plasmic-import: vLDRE8TUZ/icon
import Group4195Icon from "./icons/PlasmicIcon__Group4195"; // plasmic-import: jA2NdGFwnK/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: u3wA3h_cil/icon
import Rectangle115Icon from "./icons/PlasmicIcon__Rectangle115"; // plasmic-import: h4Bl-EXfgf/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: wyJsdEXVBs/icon

export type PlasmicEnterCode__VariantMembers = {};

export type PlasmicEnterCode__VariantsArgs = {};
type VariantPropType = keyof PlasmicEnterCode__VariantsArgs;
export const PlasmicEnterCode__VariantProps = new Array<VariantPropType>();

export type PlasmicEnterCode__ArgsType = {};
type ArgPropType = keyof PlasmicEnterCode__ArgsType;
export const PlasmicEnterCode__ArgProps = new Array<ArgPropType>();

export type PlasmicEnterCode__OverridesType = {
  root?: p.Flex<"div">;
  signUp2?: p.Flex<"div">;
  header?: p.Flex<"div">;
  headerMenu?: p.Flex<"div">;
  menuItem?: p.Flex<"div">;
  menuItem2?: p.Flex<"div">;
  features?: p.Flex<"div">;
  menuItem3?: p.Flex<"div">;
  features2?: p.Flex<"div">;
  menuItem4?: p.Flex<"div">;
  features3?: p.Flex<"div">;
  controlPanel?: p.Flex<"div">;
  input?: p.Flex<"div">;
  label?: p.Flex<"div">;
  label2?: p.Flex<"div">;
  inputField?: p.Flex<"div">;
  hintMessage?: p.Flex<"div">;
  buttonContainer?: p.Flex<"div">;
  button?: p.Flex<"div">;
  iconCopyBig?: p.Flex<"div">;
  group286?: p.Flex<"div">;
  rectangle114?: p.Flex<"div">;
  text2?: p.Flex<"div">;
  iconSelectBig?: p.Flex<"div">;
  rectangle119?: p.Flex<"div">;
  avatar?: p.Flex<"div">;
  mk?: p.Flex<"div">;
  mk2?: p.Flex<"div">;
  frame2?: p.Flex<"div">;
  frame1?: p.Flex<"div">;
  signUp?: p.Flex<"div">;
  text3?: p.Flex<"div">;
  input2?: p.Flex<"div">;
  label3?: p.Flex<"div">;
  label4?: p.Flex<"div">;
  hintMessage2?: p.Flex<"div">;
  textInput?: p.Flex<"input">;
  frame4?: p.Flex<"div">;
  button2?: p.Flex<"a"> & Partial<LinkProps>;
  iconCopyBig2?: p.Flex<"div">;
  group287?: p.Flex<"div">;
  rectangle115?: p.Flex<"div">;
  text5?: p.Flex<"div">;
  iconSelectBig2?: p.Flex<"div">;
  rectangle120?: p.Flex<"div">;
  button3?: p.Flex<"div">;
  iconCopyBig3?: p.Flex<"div">;
  group288?: p.Flex<"div">;
  rectangle116?: p.Flex<"div">;
  text6?: p.Flex<"div">;
  iconSelectBig3?: p.Flex<"div">;
  rectangle121?: p.Flex<"div">;
  rectangle122?: p.Flex<"div">;
  rectangle123?: p.Flex<"div">;
  textbox?: p.Flex<"input">;
};

export interface DefaultEnterCodeProps {}

function PlasmicEnterCode__RenderFunc(props: {
  variants: PlasmicEnterCode__VariantsArgs;
  args: PlasmicEnterCode__ArgsType;
  overrides: PlasmicEnterCode__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"signUp2"}
            data-plasmic-override={overrides.signUp2}
            className={classNames(projectcss.all, sty.signUp2)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              hasGap={true}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jU4Km
                )}
              >
                {"RateCare"}
              </div>

              {false ? (
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"headerMenu"}
                  data-plasmic-override={overrides.headerMenu}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.headerMenu)}
                >
                  <div
                    data-plasmic-name={"menuItem"}
                    data-plasmic-override={overrides.menuItem}
                    className={classNames(projectcss.all, sty.menuItem)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mLBp
                      )}
                    >
                      {"Features"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"menuItem2"}
                    data-plasmic-override={overrides.menuItem2}
                    className={classNames(projectcss.all, sty.menuItem2)}
                  >
                    <div
                      data-plasmic-name={"features"}
                      data-plasmic-override={overrides.features}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.features
                      )}
                    >
                      {"Pricing"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"menuItem3"}
                    data-plasmic-override={overrides.menuItem3}
                    className={classNames(projectcss.all, sty.menuItem3)}
                  >
                    <div
                      data-plasmic-name={"features2"}
                      data-plasmic-override={overrides.features2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.features2
                      )}
                    >
                      {"Learn"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"menuItem4"}
                    data-plasmic-override={overrides.menuItem4}
                    className={classNames(projectcss.all, sty.menuItem4)}
                  >
                    <div
                      data-plasmic-name={"features3"}
                      data-plasmic-override={overrides.features3}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.features3
                      )}
                    >
                      {"Community"}
                    </div>
                  </div>
                </p.Stack>
              ) : null}

              <p.Stack
                as={"div"}
                data-plasmic-name={"controlPanel"}
                data-plasmic-override={overrides.controlPanel}
                hasGap={true}
                className={classNames(projectcss.all, sty.controlPanel)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"input"}
                    data-plasmic-override={overrides.input}
                    className={classNames(projectcss.all, sty.input)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"label"}
                        data-plasmic-override={overrides.label}
                        className={classNames(projectcss.all, sty.label)}
                      >
                        <div
                          data-plasmic-name={"label2"}
                          data-plasmic-override={overrides.label2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label2
                          )}
                        >
                          {"Label"}
                        </div>
                      </div>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"inputField"}
                      data-plasmic-override={overrides.inputField}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.inputField)}
                    >
                      <SearchIcon
                        className={classNames(projectcss.all, sty.svg__lGaCc)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Oav
                        )}
                      >
                        {"Search"}
                      </div>

                      {false ? (
                        <Icon16PxCheckIcon
                          className={classNames(projectcss.all, sty.svg__dyP0G)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    {false ? (
                      <div
                        data-plasmic-name={"hintMessage"}
                        data-plasmic-override={overrides.hintMessage}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.hintMessage
                        )}
                      >
                        {"Hint message"}
                      </div>
                    ) : null}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={"buttonContainer"}
                    data-plasmic-override={overrides.buttonContainer}
                    className={classNames(projectcss.all, sty.buttonContainer)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        data-plasmic-name={"iconCopyBig"}
                        data-plasmic-override={overrides.iconCopyBig}
                        className={classNames(projectcss.all, sty.iconCopyBig)}
                      >
                        <div
                          data-plasmic-name={"group286"}
                          data-plasmic-override={overrides.group286}
                          className={classNames(projectcss.all, sty.group286)}
                        >
                          <div
                            data-plasmic-name={"rectangle114"}
                            data-plasmic-override={overrides.rectangle114}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle114
                            )}
                          />

                          <Rectangle116Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___7BSeM
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>

                      <div
                        data-plasmic-name={"text2"}
                        data-plasmic-override={overrides.text2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text2
                        )}
                      >
                        {"Button"}
                      </div>

                      {false ? (
                        <div
                          data-plasmic-name={"iconSelectBig"}
                          data-plasmic-override={overrides.iconSelectBig}
                          className={classNames(
                            projectcss.all,
                            sty.iconSelectBig
                          )}
                        >
                          <Group4195Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__imetc
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      {false ? (
                        <div
                          data-plasmic-name={"rectangle119"}
                          data-plasmic-override={overrides.rectangle119}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle119
                          )}
                        />
                      ) : null}
                    </p.Stack>
                  </div>
                ) : null}

                <div
                  data-plasmic-name={"avatar"}
                  data-plasmic-override={overrides.avatar}
                  className={classNames(projectcss.all, sty.avatar)}
                >
                  <Ellipse2Icon
                    className={classNames(projectcss.all, sty.svg__vs0Gb)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"mk"}
                    data-plasmic-override={overrides.mk}
                    className={classNames(projectcss.all, sty.mk)}
                  >
                    <div
                      data-plasmic-name={"mk2"}
                      data-plasmic-override={overrides.mk2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.mk2
                      )}
                    >
                      {"SR"}
                    </div>
                  </div>
                </div>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame2"}
              data-plasmic-override={overrides.frame2}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame2)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1"}
                data-plasmic-override={overrides.frame1}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1)}
              >
                <div
                  data-plasmic-name={"signUp"}
                  data-plasmic-override={overrides.signUp}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.signUp
                  )}
                >
                  {"Enter code"}
                </div>

                <div
                  data-plasmic-name={"text3"}
                  data-plasmic-override={overrides.text3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text3
                  )}
                >
                  {
                    "Enter a verification code that has been sent to +971 ** ****5527"
                  }
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"input2"}
                data-plasmic-override={overrides.input2}
                className={classNames(projectcss.all, sty.input2)}
              >
                <div
                  data-plasmic-name={"label3"}
                  data-plasmic-override={overrides.label3}
                  className={classNames(projectcss.all, sty.label3)}
                >
                  <div
                    data-plasmic-name={"label4"}
                    data-plasmic-override={overrides.label4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label4
                    )}
                  >
                    {"Verification code"}
                  </div>
                </div>

                {false ? (
                  <div
                    data-plasmic-name={"hintMessage2"}
                    data-plasmic-override={overrides.hintMessage2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.hintMessage2
                    )}
                  >
                    {"Hint message"}
                  </div>
                ) : null}
              </div>

              <input
                data-plasmic-name={"textInput"}
                data-plasmic-override={overrides.textInput ?? overrides.textbox}
                aria-label={"" as const}
                className={classNames(
                  projectcss.all,
                  projectcss.input,
                  sty.textInput
                )}
                placeholder={"6-digit code" as const}
                size={undefined}
                type={"text" as const}
                value={"" as const}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame4"}
                data-plasmic-override={overrides.frame4}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame4)}
              >
                <p.Stack
                  as={p.PlasmicLink}
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.button2
                  )}
                  component={Link}
                  href={`/home-page`}
                  platform={"nextjs"}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"iconCopyBig2"}
                      data-plasmic-override={overrides.iconCopyBig2}
                      className={classNames(projectcss.all, sty.iconCopyBig2)}
                    >
                      <div
                        data-plasmic-name={"group287"}
                        data-plasmic-override={overrides.group287}
                        className={classNames(projectcss.all, sty.group287)}
                      >
                        <div
                          data-plasmic-name={"rectangle115"}
                          data-plasmic-override={overrides.rectangle115}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle115
                          )}
                        />

                        <Rectangle115Icon
                          className={classNames(projectcss.all, sty.svg__uLbRu)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  ) : null}

                  <div
                    data-plasmic-name={"text5"}
                    data-plasmic-override={overrides.text5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text5
                    )}
                  >
                    {"Verify"}
                  </div>

                  {false ? (
                    <div
                      data-plasmic-name={"iconSelectBig2"}
                      data-plasmic-override={overrides.iconSelectBig2}
                      className={classNames(projectcss.all, sty.iconSelectBig2)}
                    >
                      <Group4195Icon
                        className={classNames(projectcss.all, sty.svg___7CgjF)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"rectangle120"}
                      data-plasmic-override={overrides.rectangle120}
                      className={classNames(projectcss.all, sty.rectangle120)}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.button3)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"iconCopyBig3"}
                      data-plasmic-override={overrides.iconCopyBig3}
                      className={classNames(projectcss.all, sty.iconCopyBig3)}
                    >
                      <div
                        data-plasmic-name={"group288"}
                        data-plasmic-override={overrides.group288}
                        className={classNames(projectcss.all, sty.group288)}
                      >
                        <div
                          data-plasmic-name={"rectangle116"}
                          data-plasmic-override={overrides.rectangle116}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle116
                          )}
                        />

                        <Rectangle115Icon
                          className={classNames(projectcss.all, sty.svg__eJo0S)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  ) : null}

                  <div
                    data-plasmic-name={"text6"}
                    data-plasmic-override={overrides.text6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text6
                    )}
                  >
                    {"Resend code"}
                  </div>

                  {false ? (
                    <div
                      data-plasmic-name={"iconSelectBig3"}
                      data-plasmic-override={overrides.iconSelectBig3}
                      className={classNames(projectcss.all, sty.iconSelectBig3)}
                    >
                      <Group4195Icon
                        className={classNames(projectcss.all, sty.svg___0IEx1)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"rectangle121"}
                      data-plasmic-override={overrides.rectangle121}
                      className={classNames(projectcss.all, sty.rectangle121)}
                    />
                  ) : null}
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <div
              data-plasmic-name={"rectangle122"}
              data-plasmic-override={overrides.rectangle122}
              className={classNames(projectcss.all, sty.rectangle122)}
            />

            <Ellipse3Icon
              className={classNames(projectcss.all, sty.svg__c0QeB)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle123"}
              data-plasmic-override={overrides.rectangle123}
              className={classNames(projectcss.all, sty.rectangle123)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "signUp2",
    "header",
    "headerMenu",
    "menuItem",
    "menuItem2",
    "features",
    "menuItem3",
    "features2",
    "menuItem4",
    "features3",
    "controlPanel",
    "input",
    "label",
    "label2",
    "inputField",
    "hintMessage",
    "buttonContainer",
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119",
    "avatar",
    "mk",
    "mk2",
    "frame2",
    "frame1",
    "signUp",
    "text3",
    "input2",
    "label3",
    "label4",
    "hintMessage2",
    "textInput",
    "textbox",
    "frame4",
    "button2",
    "iconCopyBig2",
    "group287",
    "rectangle115",
    "text5",
    "iconSelectBig2",
    "rectangle120",
    "button3",
    "iconCopyBig3",
    "group288",
    "rectangle116",
    "text6",
    "iconSelectBig3",
    "rectangle121",
    "rectangle122",
    "rectangle123"
  ],
  signUp2: [
    "signUp2",
    "header",
    "headerMenu",
    "menuItem",
    "menuItem2",
    "features",
    "menuItem3",
    "features2",
    "menuItem4",
    "features3",
    "controlPanel",
    "input",
    "label",
    "label2",
    "inputField",
    "hintMessage",
    "buttonContainer",
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119",
    "avatar",
    "mk",
    "mk2",
    "frame2",
    "frame1",
    "signUp",
    "text3",
    "input2",
    "label3",
    "label4",
    "hintMessage2",
    "textInput",
    "textbox",
    "frame4",
    "button2",
    "iconCopyBig2",
    "group287",
    "rectangle115",
    "text5",
    "iconSelectBig2",
    "rectangle120",
    "button3",
    "iconCopyBig3",
    "group288",
    "rectangle116",
    "text6",
    "iconSelectBig3",
    "rectangle121",
    "rectangle122",
    "rectangle123"
  ],
  header: [
    "header",
    "headerMenu",
    "menuItem",
    "menuItem2",
    "features",
    "menuItem3",
    "features2",
    "menuItem4",
    "features3",
    "controlPanel",
    "input",
    "label",
    "label2",
    "inputField",
    "hintMessage",
    "buttonContainer",
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119",
    "avatar",
    "mk",
    "mk2"
  ],
  headerMenu: [
    "headerMenu",
    "menuItem",
    "menuItem2",
    "features",
    "menuItem3",
    "features2",
    "menuItem4",
    "features3"
  ],
  menuItem: ["menuItem"],
  menuItem2: ["menuItem2", "features"],
  features: ["features"],
  menuItem3: ["menuItem3", "features2"],
  features2: ["features2"],
  menuItem4: ["menuItem4", "features3"],
  features3: ["features3"],
  controlPanel: [
    "controlPanel",
    "input",
    "label",
    "label2",
    "inputField",
    "hintMessage",
    "buttonContainer",
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119",
    "avatar",
    "mk",
    "mk2"
  ],
  input: ["input", "label", "label2", "inputField", "hintMessage"],
  label: ["label", "label2"],
  label2: ["label2"],
  inputField: ["inputField"],
  hintMessage: ["hintMessage"],
  buttonContainer: [
    "buttonContainer",
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119"
  ],
  button: [
    "button",
    "iconCopyBig",
    "group286",
    "rectangle114",
    "text2",
    "iconSelectBig",
    "rectangle119"
  ],
  iconCopyBig: ["iconCopyBig", "group286", "rectangle114"],
  group286: ["group286", "rectangle114"],
  rectangle114: ["rectangle114"],
  text2: ["text2"],
  iconSelectBig: ["iconSelectBig"],
  rectangle119: ["rectangle119"],
  avatar: ["avatar", "mk", "mk2"],
  mk: ["mk", "mk2"],
  mk2: ["mk2"],
  frame2: [
    "frame2",
    "frame1",
    "signUp",
    "text3",
    "input2",
    "label3",
    "label4",
    "hintMessage2",
    "textInput",
    "textbox",
    "frame4",
    "button2",
    "iconCopyBig2",
    "group287",
    "rectangle115",
    "text5",
    "iconSelectBig2",
    "rectangle120",
    "button3",
    "iconCopyBig3",
    "group288",
    "rectangle116",
    "text6",
    "iconSelectBig3",
    "rectangle121"
  ],
  frame1: ["frame1", "signUp", "text3"],
  signUp: ["signUp"],
  text3: ["text3"],
  input2: ["input2", "label3", "label4", "hintMessage2"],
  label3: ["label3", "label4"],
  label4: ["label4"],
  hintMessage2: ["hintMessage2"],
  textInput: ["textInput", "textbox"],
  frame4: [
    "frame4",
    "button2",
    "iconCopyBig2",
    "group287",
    "rectangle115",
    "text5",
    "iconSelectBig2",
    "rectangle120",
    "button3",
    "iconCopyBig3",
    "group288",
    "rectangle116",
    "text6",
    "iconSelectBig3",
    "rectangle121"
  ],
  button2: [
    "button2",
    "iconCopyBig2",
    "group287",
    "rectangle115",
    "text5",
    "iconSelectBig2",
    "rectangle120"
  ],
  iconCopyBig2: ["iconCopyBig2", "group287", "rectangle115"],
  group287: ["group287", "rectangle115"],
  rectangle115: ["rectangle115"],
  text5: ["text5"],
  iconSelectBig2: ["iconSelectBig2"],
  rectangle120: ["rectangle120"],
  button3: [
    "button3",
    "iconCopyBig3",
    "group288",
    "rectangle116",
    "text6",
    "iconSelectBig3",
    "rectangle121"
  ],
  iconCopyBig3: ["iconCopyBig3", "group288", "rectangle116"],
  group288: ["group288", "rectangle116"],
  rectangle116: ["rectangle116"],
  text6: ["text6"],
  iconSelectBig3: ["iconSelectBig3"],
  rectangle121: ["rectangle121"],
  rectangle122: ["rectangle122"],
  rectangle123: ["rectangle123"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  signUp2: "div";
  header: "div";
  headerMenu: "div";
  menuItem: "div";
  menuItem2: "div";
  features: "div";
  menuItem3: "div";
  features2: "div";
  menuItem4: "div";
  features3: "div";
  controlPanel: "div";
  input: "div";
  label: "div";
  label2: "div";
  inputField: "div";
  hintMessage: "div";
  buttonContainer: "div";
  button: "div";
  iconCopyBig: "div";
  group286: "div";
  rectangle114: "div";
  text2: "div";
  iconSelectBig: "div";
  rectangle119: "div";
  avatar: "div";
  mk: "div";
  mk2: "div";
  frame2: "div";
  frame1: "div";
  signUp: "div";
  text3: "div";
  input2: "div";
  label3: "div";
  label4: "div";
  hintMessage2: "div";
  textInput: "input";
  frame4: "div";
  button2: "a";
  iconCopyBig2: "div";
  group287: "div";
  rectangle115: "div";
  text5: "div";
  iconSelectBig2: "div";
  rectangle120: "div";
  button3: "div";
  iconCopyBig3: "div";
  group288: "div";
  rectangle116: "div";
  text6: "div";
  iconSelectBig3: "div";
  rectangle121: "div";
  rectangle122: "div";
  rectangle123: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEnterCode__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEnterCode__VariantsArgs;
    args?: PlasmicEnterCode__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicEnterCode__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicEnterCode__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicEnterCode__ArgProps,
          internalVariantPropNames: PlasmicEnterCode__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicEnterCode__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEnterCode";
  } else {
    func.displayName = `PlasmicEnterCode.${nodeName}`;
  }
  return func;
}

export const PlasmicEnterCode = Object.assign(
  // Top-level PlasmicEnterCode renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    signUp2: makeNodeComponent("signUp2"),
    header: makeNodeComponent("header"),
    headerMenu: makeNodeComponent("headerMenu"),
    menuItem: makeNodeComponent("menuItem"),
    menuItem2: makeNodeComponent("menuItem2"),
    features: makeNodeComponent("features"),
    menuItem3: makeNodeComponent("menuItem3"),
    features2: makeNodeComponent("features2"),
    menuItem4: makeNodeComponent("menuItem4"),
    features3: makeNodeComponent("features3"),
    controlPanel: makeNodeComponent("controlPanel"),
    input: makeNodeComponent("input"),
    label: makeNodeComponent("label"),
    label2: makeNodeComponent("label2"),
    inputField: makeNodeComponent("inputField"),
    hintMessage: makeNodeComponent("hintMessage"),
    buttonContainer: makeNodeComponent("buttonContainer"),
    button: makeNodeComponent("button"),
    iconCopyBig: makeNodeComponent("iconCopyBig"),
    group286: makeNodeComponent("group286"),
    rectangle114: makeNodeComponent("rectangle114"),
    text2: makeNodeComponent("text2"),
    iconSelectBig: makeNodeComponent("iconSelectBig"),
    rectangle119: makeNodeComponent("rectangle119"),
    avatar: makeNodeComponent("avatar"),
    mk: makeNodeComponent("mk"),
    mk2: makeNodeComponent("mk2"),
    frame2: makeNodeComponent("frame2"),
    frame1: makeNodeComponent("frame1"),
    signUp: makeNodeComponent("signUp"),
    text3: makeNodeComponent("text3"),
    input2: makeNodeComponent("input2"),
    label3: makeNodeComponent("label3"),
    label4: makeNodeComponent("label4"),
    hintMessage2: makeNodeComponent("hintMessage2"),
    textInput: makeNodeComponent("textInput"),
    frame4: makeNodeComponent("frame4"),
    button2: makeNodeComponent("button2"),
    iconCopyBig2: makeNodeComponent("iconCopyBig2"),
    group287: makeNodeComponent("group287"),
    rectangle115: makeNodeComponent("rectangle115"),
    text5: makeNodeComponent("text5"),
    iconSelectBig2: makeNodeComponent("iconSelectBig2"),
    rectangle120: makeNodeComponent("rectangle120"),
    button3: makeNodeComponent("button3"),
    iconCopyBig3: makeNodeComponent("iconCopyBig3"),
    group288: makeNodeComponent("group288"),
    rectangle116: makeNodeComponent("rectangle116"),
    text6: makeNodeComponent("text6"),
    iconSelectBig3: makeNodeComponent("iconSelectBig3"),
    rectangle121: makeNodeComponent("rectangle121"),
    rectangle122: makeNodeComponent("rectangle122"),
    rectangle123: makeNodeComponent("rectangle123"),

    // Metadata about props expected for PlasmicEnterCode
    internalVariantProps: PlasmicEnterCode__VariantProps,
    internalArgProps: PlasmicEnterCode__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicEnterCode;
/* prettier-ignore-end */
