// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7zgBTwbPpHbjHNGdtqUv3x
// Component: G6iO0OlBUS
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: QtbTn9PNS3o/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 7zgBTwbPpHbjHNGdtqUv3x/projectcss
import sty from "./PlasmicCancelButton.module.css"; // plasmic-import: G6iO0OlBUS/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: N_rBuzKEqCD/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 8Xy2TdC8dVc/icon

export type PlasmicCancelButton__VariantMembers = {};

export type PlasmicCancelButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicCancelButton__VariantsArgs;
export const PlasmicCancelButton__VariantProps = new Array<VariantPropType>();

export type PlasmicCancelButton__ArgsType = {};
type ArgPropType = keyof PlasmicCancelButton__ArgsType;
export const PlasmicCancelButton__ArgProps = new Array<ArgPropType>();

export type PlasmicCancelButton__OverridesType = {
  root?: p.Flex<typeof Button>;
};

export interface DefaultCancelButtonProps {
  className?: string;
}

function PlasmicCancelButton__RenderFunc(props: {
  variants: PlasmicCancelButton__VariantsArgs;
  args: PlasmicCancelButton__ArgsType;
  overrides: PlasmicCancelButton__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <Button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    >
      {"Cancel"}
    </Button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCancelButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCancelButton__VariantsArgs;
    args?: PlasmicCancelButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCancelButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCancelButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCancelButton__ArgProps,
          internalVariantPropNames: PlasmicCancelButton__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCancelButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCancelButton";
  } else {
    func.displayName = `PlasmicCancelButton.${nodeName}`;
  }
  return func;
}

export const PlasmicCancelButton = Object.assign(
  // Top-level PlasmicCancelButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCancelButton
    internalVariantProps: PlasmicCancelButton__VariantProps,
    internalArgProps: PlasmicCancelButton__ArgProps
  }
);

export default PlasmicCancelButton;
/* prettier-ignore-end */
